# This is a basic workflow to help you get started with Actions

name: buildroot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  [push, pull_request, workflow_dispatch]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install buildroot
        run: |
          wget "https://buildroot.org/downloads/buildroot-2020.08.tar.gz"
          tar xzf buildroot-2020.08.tar.gz

      - name: Build buildroot
        run: |
          cd sw/buildroot
          make -C $GITHUB_WORKSPACE/buildroot-2020.08 O=$PWD BR2_EXTERNAL=$PWD beagleconnect_gateway_qemu_x86_64_defconfig
          make

      - uses: actions/upload-artifact@v2
        with:
          name: buildroot
          path: sw/buildroot/{host,images}
